name: remote ssh command
on: [push]

env:
  FOO: "BAR"
  BAR: "FOO"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: Saikrishnareddy12345/ReactAppSample@main
        env:
              PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
              HOSTNAME : ${{ secrets.HOSTNAME  }}
              USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            
              #Now we have got the access of EC2 and we will start the deploy .
              cd /home/ec2-user/react &&
              git fetch --all &&
              git pull origin main &&
              cd /home/ec2-user/react/ &&
              npm install
              npm audit fix --force
              yarn install
              yarn start 
              '
          