name: Remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: Saikrishnareddy12345/ReactAppSample@main
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/home/ec2-user/react/Snapshot
            npm install
            npm audit fix --force
            npm start
            